//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roostersysteem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persoon()
        {
            this.Authenticators = new HashSet<Authenticator>();
            this.PersoonUrens = new HashSet<PersoonUren>();
            this.PersoonVaks = new HashSet<PersoonVak>();
        }
    
        public int PersoonId { get; set; }
        public string PersoonVoornaam { get; set; }
        public string PersoonAchternaam { get; set; }
        public Nullable<int> PersoonTelefoonnummer { get; set; }
        public string PersoonEmail { get; set; }
        public string PersoonStraat { get; set; }
        public Nullable<int> PersoonHuisnummer { get; set; }
        public string PersoonToevoegingHuisnr { get; set; }
        public string PersoonWoonplaats { get; set; }
        public string PersoonPostcode { get; set; }
        public string PersoonGebruikersnaam { get; set; }
        public string PersoonWachtwoord { get; set; }
        public string PersoonFunctie { get; set; }
        public Nullable<int> PersoonContractUren { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authenticator> Authenticators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersoonUren> PersoonUrens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersoonVak> PersoonVaks { get; set; }
    }
}
