//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roostersysteem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooster
    {
        public int RoosterId { get; set; }
        public Nullable<int> PersoonVak_Id { get; set; }
        public Nullable<int> VakUrenCollege_Id { get; set; }
        public string Klas { get; set; }
        public Nullable<int> VakLokaalType_Id { get; set; }
    
        public virtual PersoonVak PersoonVak { get; set; }
        public virtual VakLokaalType VakLokaalType { get; set; }
        public virtual VakUrenCollege VakUrenCollege { get; set; }
    }
}
